# Generated by Django 3.0.1 on 2020-02-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200202_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='confirm_password',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
