# Generated by Django 3.0.1 on 2020-01-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('p_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.Person')),
                ('adhar_card', models.CharField(max_length=32)),
                ('pan_card', models.CharField(max_length=32)),
            ],
        ),
    ]
