# Generated by Django 3.0.1 on 2020-01-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Customer'),
        ),
    ]
