# Generated by Django 3.0.1 on 2020-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200122_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phno', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=32)),
                ('fees', models.CharField(max_length=32)),
                ('students', models.ManyToManyField(to='app1.Student')),
            ],
        ),
    ]
