# Generated by Django 3.0.1 on 2020-01-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_student_tution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no1', models.IntegerField()),
                ('no2', models.BigIntegerField()),
                ('no3', models.FloatField()),
                ('choice', models.BooleanField()),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
