# Generated by Django 3.0.1 on 2020-01-23 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('no1', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(help_text='Enter address')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
