# Generated by Django 3.0.1 on 2020-01-23 15:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200123_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
