# Generated by Django 3.0.1 on 2020-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='active',
        ),
        migrations.RemoveField(
            model_name='details',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='details',
            name='last_logged_in',
        ),
        migrations.AddField(
            model_name='details',
            name='address1',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='address2',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='city',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='password',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('UP', 'Uttar Pradesh')], default='UP', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='zip1',
            field=models.IntegerField(default=True),
        ),
    ]
