# Generated by Django 3.0.1 on 2020-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
