# Generated by Django 3.0.1 on 2020-02-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_details_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='confirm_password',
            field=models.CharField(max_length=50),
        ),
    ]
