# Generated by Django 3.0.1 on 2020-02-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200204_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
